.TH "AUDIT_FLAG_TO_NAME" "3" "Mar 2022" "Red Hat" "Linux Audit API"
.SH NAME
audit_flag_to_name \- Convert the numeric rule-matching filter value to the rule-matching filter name
.SH "SYNOPSIS"
.nf
.B #include <libaudit.h>
.PP
.BI "const char *audit_flag_to_name(int " flag );
.fi
.SH "DESCRIPTION"
.BR audit_flag_to_name ()
converts the numeric rule-matching filter value (AUDIT_FILTER_TASK, AUDIT_FILTER_EXIT, AUDIT_FILTER_USER, AUDIT_FILTER_EXCLUDE, AUDIT_FILTER_FS) to the rule-matching filter name ("task", "exit", "user", "exclude", "filesystem").
.I flag
is the numeric rule-matching filter value.

.SH "RETURN VALUE"

Returns NULL if an error occurs; otherwise, the return value is the rule-matching filter name.

.SH "SEE ALSO"

.BR audit_name_to_flag (3),

.SH AUTHOR
Steve Grubb
