.TH "AUPARSE_SET_EOE_TIMEOUT" "3" "January 2021" "Red Hat" "Linux Audit API"
.SH NAME
auparse_set_eoe_timeout \- set the end of event timeout value
.SH "SYNOPSIS"
.B #include <auparse.h>
.sp
int auparse_set_eoe_timeout(time_t new_tmo)

.SH "DESCRIPTION"

auparse_set_eoe_timeout is used to set the end of event timeout value (seconds). The value should be a positive integer. If this function is called, it overrides any setting in /etc/auditd.conf.
The function should be called after the \fIauparse_init()\fP function call.

For details on the timeout, see the \fBend_of_event_timeout\fP configuration item description in \fIauditd.conf(5)\fP.

.SH "RETURN VALUE"

Returns \-1 if an error occurs; otherwise, 0 for success.

.SH "SEE ALSO"

.BR auparse_init (3).
.BR auditd.conf (8).

.SH AUTHOR
Steve Grubb
