.\" Copyright (C) 2004 IBM
.\" This file is distributed according to the GNU General Public License.
.\" See the file COPYING in the top level source directory for details.
.TH "SET_AUMESSAGE_MODE" 3 "2004-12-01" "Linux 2.6" "Linux Programmer's Manual"
.SH NAME
set_aumessage_mode \- Sets the message mode
.SH "SYNOPSIS"
.nf
.B #include <libaudit.h>
.PP
.BI "void set_aumessage_mode(message_t " mode ", debug_message_t " debug ");"
.fi

.SH "DESCRIPTION"

.PP
\fBset_aumessage_mode\fR sets the location where messages are sent and the output of the debug messages.

If \fImode\fR=MSG_STDERR, then messages are sent to stderr. If \fImode\fR=MSG_SYSLOG, then messages are sent to syslog. If \fImode\fR=MSG_QUIET (default), then messages are not sent.

If \fIdebug\fR=DBG_YES, then debug messages are output. If \fIdebug\fR=DBG_NO (default), then debug messages are not output.

.SH "EXAMPLE"

.nf

/* Sample code */
set_aumessage_mode(MSG_SYSLOG, DBG_YES)

.fi

.SH "RETURN VALUE"

None.

.SH "SEE ALSO"

.BR auditd (8),
.BR audit_open (3).

.SH AUTHOR
Debora Velarde.
